repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Use the latest stable version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict

  - repo: https://github.com/psf/black
    rev: 23.1.0  # Black version
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.17.4
    hooks:
      - id: pylint

  - repo: local
    hooks:
      - id: pytest
        name: Allow Partial Test Pass
        entry: bash -c 'pytest || echo "Tests failed, but commit allowed!"'
        language: system
        pass_filenames: false
